### ISSUE TITLE
Implement constraints on predicted prevalence (demographic parity)

### ISSUE THREAD

**Issue by AndreFCruz** [feedzai/fairgbm#42]
## Summary

We should enable creating group-wise constraints on the percentage of positive predictions (a.k.a., predicted prevalence).

This enables the popular _Demographic Parity_ fairness metric.

**TODO**
- [ ] Add `constraint_type=PP` to the available group-wise constraint options;
- [ ] Implement gradient descent on proxy _predicted prevalence_ metrics;
- [ ] Add the same `PP` constraint type for global constraints
  - This would be a constraint on maximum alert rate -> quite useful for our in-house use cases

_EDIT_

Minor notes for the future PP constraint implementation: 
[83de2426-ea6e-4308-9f0d-5ddc3b001580.pdf](https://github.com/feedzai/fairgbm/files/9583351/83de2426-ea6e-4308-9f0d-5ddc3b001580.pdf)
